//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMprojectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationHistory
    {
        public int CommID { get; set; }
        public string CommType { get; set; }
        public string CommDate { get; set; }
        public string CommSubject { get; set; }
        public string CommContent { get; set; }
        public string CommStatus { get; set; }
        public Nullable<int> CommCustomerID { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
