//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMprojectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int saleID { get; set; }
        public Nullable<System.DateTime> saleDate { get; set; }
        public string saleQuantity { get; set; }
        public string saleUnitPrice { get; set; }
        public string saleDiscountRate { get; set; }
        public Nullable<int> saleCustomerID { get; set; }
        public Nullable<int> saleProductID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Products Products { get; set; }
    }
}
