//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMprojectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int taskID { get; set; }
        public string taskName { get; set; }
        public string taskDescription { get; set; }
        public Nullable<System.DateTime> taskStartDate { get; set; }
        public Nullable<System.DateTime> taskEndDate { get; set; }
        public string taskStatus { get; set; }
        public Nullable<int> taskUserID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
